config/routes.rb
Rails.application.routes.draw do 
  match 'site_translations' => 'GoTranslateYourself::SiteTranslations#edit', :as => :site_translations, :method => :get
  match 'site_translations/save' => 'GoTranslateYourself::SiteTranslations#update', :as => :update_site_translations, :method => :post
end

app/controllers/go_translate_yourself/site_translations_controller.rb
module GoTranslateYourself
  class SiteTranslationsController < ApplicationController
    before_filter :auth

    def edit
      @translations = hash_class[
        *GoTranslateYourself.current_store.keys_without_prefix.collect do |key| 
          [key, GoTranslateYourself.current_store.default_translation("dev.#{key}")]
        end.flatten
      ]
      @locales = GoTranslateYourself.locales
      render :layout => GoTranslateYourself.layout_name
    end

    def update
      if params[:translations] && !params[:translations].empty?
        params[:translations].each do |key, value|
          GoTranslateYourself.current_store[key] = value
        end
      end
      redirect_to site_translations_path, :notice => "Successful save"
    end

    private

    def auth
      GoTranslateYourself.auth_handler.bind(self).call if GoTranslateYourself.auth_handler.is_a? Proc
    end

    def hash_class
      RUBY_VERSION < '1.9' ? ActiveSupport::OrderedHash : Hash
    end
  end
end

app/helpers/go_translate_yourself/site_translations_helper.rb
module GoTranslateYourself
  module SiteTranslationsHelper
    def translation_text_field(locale, key, default_translation)
      options = { :size => (default_translation.size + 20),
                  :id => "translations_#{locale}_#{key}".gsub(/\./, '_') }

      options[:disabled] = "disabled" if GoTranslateYourself.current_store.default_translation?("#{locale}.#{key}")
      text_field_tag("translations[#{locale}.#{key}]", 
                     ActiveSupport::JSON.decode(GoTranslateYourself.current_store["#{locale}.#{key}"] || ""), 
                     options)
    end
  end
end

app/views/go_translate_yourself/site_translations/edit.html.erb
<%= form_tag update_site_translations_path, :method => :post do %>
  <table class="gt_site_translations">
    <tr class="gt_ths">
      <th>Key</th>
      <th>Value</th>
    </tr>
    <% @translations.each do |key, default_translation| %>
      <tr class="gt_separator">
        <td colspan="2"></td>
      </tr>
      <tr class="gt_default_value">
        <td class="gt_key">
          <a name="<%= key %>" href="#<%= key %>"><%= key %></a>
        </td>
        <td class="gt_value">
          <%= default_translation %>
        </td>
        <% @locales.each do |locale| %>
          <tr>
            <td>
              <%= locale %>
            </td>
            <td>
              <%= translation_text_field locale, key, default_translation %>
            </td>
          </tr>
        <% end %>
      </tr>
    <% end %>
  </table>
  <%= submit_tag "Save" %>
<% end %>